-- Schema bootstrap for the ranking backend.
-- This migration does not import, seed, delete, or rewrite score rows.

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  score integer not null,
  diff text not null,
  level integer not null,
  won boolean not null default false,
  country text not null default '',
  city text not null default '',
  device text not null default ''
);

alter table public.scores enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_name_length'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_name_length check (char_length(name) between 1 and 16);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_score_valid'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_score_valid check (score between 0 and 999999999);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_level_valid'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_level_valid check (level between 1 and 6);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_diff_valid'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_diff_valid check (
        diff in (
          'El Diávolo (fácil)',
          'Chorizo Mezcla (medio)',
          'Mansa Gorda (difícil)'
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_country_length'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_country_length check (char_length(country) <= 40);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_city_length'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_city_length check (char_length(city) <= 60);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scores_device_valid'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_device_valid check (device in ('', 'desktop', 'touch'));
  end if;
end $$;

create index if not exists scores_score_created_at_idx
  on public.scores (score desc, created_at asc);

grant usage on schema public to anon;
grant select, insert on public.scores to anon;
grant usage, select on sequence public.scores_id_seq to anon;

drop policy if exists "scores are publicly readable" on public.scores;
create policy "scores are publicly readable"
on public.scores
for select
to anon
using (true);

drop policy if exists "players can submit valid scores" on public.scores;
create policy "players can submit valid scores"
on public.scores
for insert
to anon
with check (
  char_length(name) between 1 and 16
  and score between 0 and 999999999
  and level between 1 and 6
  and diff in (
    'El Diávolo (fácil)',
    'Chorizo Mezcla (medio)',
    'Mansa Gorda (difícil)'
  )
  and char_length(country) <= 40
  and char_length(city) <= 60
  and device in ('', 'desktop', 'touch')
);
